spring:
  application:
    name: digitalLibraryPractice
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Jeeva@2512
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
#  data:
#    redis:
#      host:
#      port:
#      password:
#  security:
#    user:
#      name: "Jeevan"
#      password: "Jeevan"
